# Generated by Django 5.2.4 on 2025-07-26 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('POST', '게시글'), ('COMMENT', '댓글')], default='POST', max_length=10, verbose_name='타입')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='제목')),
                ('content', models.TextField(verbose_name='본문')),
                ('writer', models.CharField(max_length=100, verbose_name='작성자')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('group_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='그룹 ID')),
                ('depth', models.PositiveIntegerField(default=0, verbose_name='댓글 깊이')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='bbs.bbs', verbose_name='부모 댓글')),
            ],
            options={
                'verbose_name': '게시글 및 댓글',
                'verbose_name_plural': '게시글 및 댓글',
                'ordering': ['group_id', 'created_at'],
            },
        ),
    ]
