# Generated by Django 5.2.4 on 2025-07-28 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbs',
            options={'managed': False, 'ordering': ['group_id', 'created_at'], 'verbose_name': '게시글 및 댓글', 'verbose_name_plural': '게시글 및 댓글'},
        ),
    ]
