# Generated by Django 5.2.4 on 2025-07-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_alter_bbs_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bbs',
            table='bbs',
        ),
    ]
