# Generated by Django 5.2.4 on 2025-07-28 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_alter_bbs_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bbs',
        ),
    ]
