# Generated by Django 5.2.4 on 2025-07-29 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildBbs',
            fields=[
                ('bbs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bbs.bbs')),
            ],
            bases=('bbs.bbs',),
        ),
    ]
