# Generated by Django 5.2.4 on 2025-07-29 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_childbbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='BbsFile',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/')),
                ('orig_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bbs', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='bbs.bbs')),
            ],
            options={
                'verbose_name': '게시글 첨부파일',
                'verbose_name_plural': '게시글 첨부 파일',
                'db_table': 'bbs_files',
                'managed': True,
            },
        ),
    ]
